"""Core functions for dialogify"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['get_main', 'clean_txt', 'get_title', 'get_sections', 'preview_msgs', 'html_to_md', 'html_to_md_children', 'has_cls',
           'get_msg_type', 'collect_msgs', 'format_msg', 'merge_dt', 'format_msgs', 'create_msgs', 'mk_dialog']

# %% ../nbs/00_core.ipynb 6
from dialoghelper import *
from dialoghelper.capture import *
from fastcore.utils import *

from IPython.display import Markdown, display
from bs4 import BeautifulSoup, NavigableString
import httpx

from itertools import groupby as igroupby


# %% ../nbs/00_core.ipynb 12
def get_main(soup):
    "Extract the main content section from Python docs soup"
    return soup.select_one('div.body > section')

# %% ../nbs/00_core.ipynb 14
def clean_txt(el):
    "Clean element text by removing paragraph signs and extra whitespace"
    return el.get_text().replace('¶', '').strip()

# %% ../nbs/00_core.ipynb 15
def get_title(section):
    "Extract the h1 title from a section"
    if (h1 := section.find('h1')): return clean_txt(h1)

# %% ../nbs/00_core.ipynb 18
def get_sections(main):
    "Get all direct child sections as (title, section_element) tuples"
    return [(clean_txt(s.find('h2')), s) for s in main.find_all('section', recursive=False) if s.find('h2')]

# %% ../nbs/00_core.ipynb 23
def preview_msgs(msgs):
    """Preview message tuples as rendered markdown"""
    for msg_type, content in msgs:
        display(Markdown(f"**[{msg_type}]**\n\n{content}"))

# %% ../nbs/00_core.ipynb 26
def html_to_md(el, in_link=False):
    """Recursively convert HTML element to markdown string"""
    if isinstance(el, NavigableString): return str(el)

    children_md = html_to_md_children(el, in_link=el.name=='a')

    match el.name:
        case 'a': return f"[{children_md}]({el.get('href', '')})"
        case 'code': return children_md if in_link else f"`{children_md}`"
        case 'em': return f"*{children_md}*"
        case 'strong': return f"**{children_md}**"
        case 'li': return f"- {children_md}"
        case _: return children_md

# %% ../nbs/00_core.ipynb 27
def html_to_md_children(el, in_link=False): return ''.join(html_to_md(child, in_link) for child in el.children)

# %% ../nbs/00_core.ipynb 31
def has_cls(el, cls): return cls in ' '.join(el.get('class', []))

# %% ../nbs/00_core.ipynb 33
def get_msg_type(el):
    match el.name:
        case 'h1': return ('note', el)
        case 'h2': return ('note', el)
        case 'div' if has_cls(el, 'highlight'): return ('code', el)
        case 'div' if has_cls(el, 'admonition'): return ('note', el)
        case 'p': return ('note', el)
        case 'ul': return ('note', el)
        case 'dt': return ('dt', el)

# %% ../nbs/00_core.ipynb 34
def collect_msgs(el):
    res = get_msg_type(el)
    if res: return [res]
    msgs = []
    for o in el.children:
        if not isinstance(o, NavigableString):
            msgs.extend(collect_msgs(o))
    return msgs

# %% ../nbs/00_core.ipynb 35
def format_msg(msg_type, el):
    def r(ct): return (msg_type, ct)
    match el.name:
        case 'h1': return r(f"# {clean_txt(el)}")
        case 'h2': return r(f"## {clean_txt(el)}")
        case 'dt': return r(f"### `{clean_txt(el)}`")
        case 'div' if has_cls(el, 'admonition'):
            t = el.select_one('p.admonition-title')
            cts = '\n>\n> '.join([html_to_md(o) for o in t.find_next_siblings()])
            return r(f"> **{html_to_md(t)}**: {cts}")
        case _: return r(html_to_md(el))

# %% ../nbs/00_core.ipynb 37
def merge_dt(msgs):
    res = []
    for t, grp in igroupby(msgs, first):
        if t == 'dt': res.append(('note', '\n'.join(o[1] for o in grp)))
        else: res.extend(grp)
    return res

# %% ../nbs/00_core.ipynb 38
def format_msgs(el): return merge_dt([format_msg(t, e) for t, e in collect_msgs(el)])

# %% ../nbs/00_core.ipynb 47
def create_msgs(doc_tuples, dname='', **kwargs):
    """Create solveit messages from list of (msg_type, content) tuples"""
    for msg_type, ct in doc_tuples: add_msg(content=ct, msg_type=msg_type, placement='at_end' if dname else 'add_after', **kwargs)

# %% ../nbs/00_core.ipynb 50
def mk_dialog(url, dname=''):
    """Fetch Python docs URL and create a solveit dialog from it"""
    if dname and not (p := Path(f'{dname}.ipynb')).exists(): p.write_json({"cells":[],"metadata":{},"nbformat":4,"nbformat_minor":5})
    html = httpx.get(url).text
    soup = BeautifulSoup(html, 'html.parser')
    main = get_main(soup)
    create_msgs(format_msgs(main), dname=dname)
